In [1]:
#          Copyright Rein Halbersma 2018-2020.
# Distributed under the Boost Software License, Version 1.0.
#    (See accompanying file LICENSE_1_0.txt or copy at
#          http://www.boost.org/LICENSE_1_0.txt)

# Common Stratego Game Setups by Piece

## Re-implementing Dobby125's [blog post](http://stratego-tips.blogspot.com/2017/04/common-stratego-piece-placements.html)

In [2]:
import numpy as np

import gravon.package as pkg
from gravon.piece import Rank, rank_names, rank_counts

df = pkg.load_dataset('ss2').query('ext == ".xml" & type == "classic"')
count, probs = df.setup_obj.apply(lambda x: x.tensor).agg(['sum', 'mean'])

In [3]:
np.set_printoptions(formatter={'float': '{:7.2%}'.format}, linewidth=100)

print(f'The charts below show Stratego piece placements from {df.shape[0]:,} setups.\n')
for r in list(reversed(range(Rank._1, Rank._B))) + [ Rank._B, Rank._F ]:
    print(f'Common Stratego {rank_names[r].capitalize()} Placement\n')
    print(f'{np.flip(count[r], axis=1)}\n')
    print(f'{np.sum (count[r], axis=1)} {np.sum (count[r])}\n')
    print(f'{np.flip(probs[r], axis=1)}\n')
    print(f'{np.sum (probs[r], axis=1) / rank_counts["classic"][r]}\n')

np.set_printoptions()

The charts below show Stratego piece placements from 84,956 setups.

Common Stratego Marshal Placement

[[ 289  168   92   92  158  181  103  130  157  328]
 [ 852 1760 1392  855 1787 1760  929 1263 1550 1241]
 [2487 2932 5612 5246 3521 4196 5546 5427 2712 2494]
 [ 379  651 6004 7438  610  644 7051 5948  515  456]]

[ 1698 13389 40173 29696] 84956

[[  0.34%   0.20%   0.11%   0.11%   0.19%   0.21%   0.12%   0.15%   0.18%   0.39%]
 [  1.00%   2.07%   1.64%   1.01%   2.10%   2.07%   1.09%   1.49%   1.82%   1.46%]
 [  2.93%   3.45%   6.61%   6.17%   4.14%   4.94%   6.53%   6.39%   3.19%   2.94%]
 [  0.45%   0.77%   7.07%   8.76%   0.72%   0.76%   8.30%   7.00%   0.61%   0.54%]]

[  2.00%  15.76%  47.29%  34.95%]

Common Stratego General Placement

[[ 199  175  104  101  128  111   73  103  160  245]
 [ 857 1062 1044  808 1464 1551  653 1065 1109  810]
 [2769 3382 5777 5890 6844 5012 4866 5405 3149 2422]
 [ 517  609 5202 7487  543  552 7284 4353  657  414]]

[ 1399 10423 45516 27618] 84956